config/routes.rb
Rails.application.routes.draw do
  # static_pagesコントローラのhomeアクション（homeビュー）をルートに指定
  root to: 'static_pages#home'
  # GETリクエスト /signup を usersコントローラのnewアクションに割り当て
  get 'signup', to: 'users#new'
  # GETリクエスト /login を sessionsコントローラのnewアクションに割り当て
  get 'login' => 'sessions#new'
  # 
  post 'login' => 'sessions#create'
  # 
  delete 'logout' => 'sessions#destroy'
  
  # RESTfulなURLを自動生成
  resources :users do
    member do
      get 'followings'
      get 'followers'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  # user_idが存在する   
  validates :user_id, presence: true
  # contentが存在し、文字数は最大140
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
    # データの保存前にメールアドレスのアルファベットを小文字にする。
    before_save { self.email = email.downcase }
    # nameは入力必須。最大50文字
    validates :name , presence: true, length: {maximum: 50}
    # メールアドレスの正規表現パターンを定義
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    # emailは入力必須。255文字以内でVALID_EMAIL_REGEXのパターンに一致。
    # 一意であること（大文字小文字は区別しない）
    validates :email, presence: true, length: {maximum: 255},
                      format: {with: VALID_EMAIL_REGEX},
                      uniqueness: { case_sensitive: false }

    # 認証機能を追加
    has_secure_password
    # 各ユーザーは複数の投稿を持つ
    has_many :microposts
    # ユーザーは複数のfollowing_relationshipsを持つ
    # following_relationshipsは、follwer_idを外部キーとし
    # 関連するユーザーが削除された場合、同時に削除される
    has_many :following_relationships, class_name: "Relationship",
                                       foreign_key: "follower_id",
                                       dependent: :destroy
    # ユーザーはfollowing_relationshipsのfollowed_idを介して、複数のfollowing_usersを持つ
    has_many :following_users, through: :following_relationships, source: :followed
    # ユーザーは複数のfollower_relationshipsを持つ
    # follower_relationshipsは、follower_idを外部キーとし、ユーザーが削除されたら削除
    has_many :follower_relationships, class_name: "Relationship",
                                      foreign_key: "followed_id",
                                      dependent: :destroy
    # ユーザーはfollower_relationshipsのfollower_idを介して、複数のfollower_usersを持つ
    has_many :follower_users, through: :follower_relationships, source: :follower
    
    # 他のユーザーをフォローする
    def follow(other_user)
        following_relationships.create(followed_id: other_user.id)
    end
    
    # フォローしているユーザーをアンフォローする
    def unfollow(other_user)
        following_relationships.find_by(followed_id: other_user.id).destroy
    end
    
    # あるユーザーをフォローしているかどうか？
    def following?(other_user)
        following_users.include?(other_user)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # SessionsHelperの読み込み
  include SessionsHelper
  
  private
  def logged_in_user
    # ユーザーがログインしていない場合
    unless logged_in?
      # アクセスしようとしたURLをセッションに一時保存する
      store_location
      # フラッシュメッセージに警告を表示
      flash[:danger] = "Please log in"
      # ログイン画面に遷移（リダイレクトの場合は絶対パスの'*_url'を使う）
      redirect_to login_url
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    # ログインしていない場合は、createメソッドを実行せず/loginにリダイレクト
    before_action :logged_in_user, only: [:create]
    
    def create
        # 入力されたパラメータを元にMicropostのインスタンスを生成
        @micropost = current_user.microposts.build(micropost_params)
        # micropostの保存に成功した場合
        if @micropost.save
            flash[:success] = "Micropost created!"
            # rootにリダイレクト
            redirect_to root_url
        else
            # homeパーシャルを読み込み
            render 'static_pages/home'
        end
    end
    
    def destroy
        @micropost = current_user.microposts.find_by(id: params[:id])
        # 投稿が現在のユーザーのものでなければ、ルートに遷移
        return redirect_to root_url if @micropost.nil?
        # 投稿を削除
        @micropost.destroy
        # フラッシュメッセージを指定
        flash[:success] = "Micropost deleted"
        # 遷移元URLまたは（なければ）ルートに遷移
        redirect_to request.referrer || root_url
    end
    
    private
    def micropost_params
        # 入力されたパラメータのうち、contentのみを許可
        params.require(:micropost).permit(:content)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :logged_in_user
    
    # フォローする
    def create
        @user = User.find(params[:followed_id])
        current_user.follow(@user)
    end
    
    # アンフォローする
    def destroy
        # 現在のユーザーのfollowing_relationshipsを検索して、フォローされているユーザーを取得
        @user = current_user.following_relationships.find(params[:id]).followed
        current_user.unfollow(@user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    # 入力されたメールアドレス（小文字化）でUserデータベースを検索
    @user = User.find_by(email: params[:session][:email].downcase)
    # @userが見つかり、かつ、パスワードが正しい場合
    if @user && @user.authenticate(params[:session][:password])
      # sessionのuser_idに入力されたidを保存
      session[:user_id] = @user.id
      # フラッシュメッセージを表示
      flash[:info] = "logged in as #{@user.name}"
      # @userのページを表示
      redirect_to @user
    # @userが見つからない、あるいは、パスワードが正しくない場合
    else
      # エラーメッセージを表示
      flash[:danger] = 'invalid email/password combination'
      # newテンプレートを表示
      render 'new'
    end
  end
  
  def destroy
    # sessionに保存されたuser_idを破棄する
    session[:user_id] = nil
    # rootに遷移
    redirect_to root_path
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    # ログインユーザーの場合、投稿のインスタンスを生成(user_idが紐付いている)
    @micropost = current_user.microposts.build if logged_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # edit, updateアクションの前に、set_userメソッドを実行
  before_action :set_user, only: [:show, :edit, :update, :followings, :followers]
  
  def show
    @following_users = @user.following_users
    @follower_users = @user.follower_users
    # ログインユーザーの投稿を取得
    @microposts = @user.microposts
  end
  
  def new
    # Userインスタンスの新規作成
    @user = User.new
  end
  
  def create
    # 送信されたパラメータを元に新しいUserインスタンスを生成
    @user = User.new(user_params)
    if @user.save
      # フラッシュメッセージを指定
      flash[:success] = "Welcome to the Sample App!"
      # データベースへの保存に成功した場合、@userの詳細画面にリダイレクトする
      redirect_to @user
    else
      # データベースへの保存に失敗した場合、newテンプレートを出力
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(profile_params)
      flash[:success] = "Your Profile is updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  # フォローしているユーザーを表示する
  def followings
    @following_users = @user.following_users
  end
  
  # フォローされているユーザーを表示する
  def followers
    @follower_users = @user.follower_users
  end
  
  private
  
  def user_params
    # 入力パラメータとして、userのname, email, password, password_confirmationのみ許可する（受け取る）
    params.require(:user).permit(:name, :email, :password, 
                                 :password_confirmation)
  end
  
  def profile_params
    params.require(:user).permit(:name, :email, :profile, :location)
  end
  
  def set_user
    # Userデータベースをidで検索
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # 現在のログインしているユーザーを返すメソッド
    def current_user
        # @current_userがfalseあるいはnilの場合に、現在ログインしているuserを取得
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    # ユーザーがログイン状態かどうかを返すメソッド
    def logged_in?
        # curret_userが存在する場合はtrue、存在しない場合はfalseを返す
        !!current_user
    end
    
    # アクセスしたいURLを一時保存するためのメソッド
    def store_location
        # リクエストがGETの場合は、リクエストのURLを代入
        session[:forwarding_url] = request.url if request.get?
    end
end

app/helpers/users_helper.rb
module UsersHelper
    # 与えられたuserのGravatarを返す
    def gravatar_for(user, options = { size: 80 })
        # メールアドレスをMD5ハッシュ化
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        # 画像のサイズを縦横80pxに指定
        size = options[:size]
        # gravatarの画像用のURL
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        # imageタグを生成
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end
        

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "Microposts", root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Help", '#' %></li>
                <!-- ログインしている場合-->
                <% if logged_in? %>
                    <!-- ユーザー情報を表示する -->
                    <li><%= link_to "Users", '#' %></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Account <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Profile", current_user %></li>
                            <li><%= link_to "Setteings", edit_user_path(current_user) %></li>
                            <li class="divider">
                                <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                            </li>
                        </ul>
                    </li>
                <!-- ログインしていない場合 -->
                <% else %>
                    <!-- ログイン画面へのリンクを表示する -->
                    <li><%= link_to "Log in", login_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microposts</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <!-- フラッシュメッセージを出力（ハッシュのキー：message_typeと値：message）-->
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <%= message %>
      </div>
    <% end %>
    <!-- コントローラで処理された内容を埋め込む -->
    <%= yield %>
  </div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
    <!-- Gravatarへのリンクを表示 -->
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
    <!-- 投稿したユーザーの詳細画面へのリンクを表示 -->
    <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    <!-- 投稿を表示 -->
    <span class="content"><%= micropost.content %></span>
    <!-- -->
    <span class="timestamp">
        <!-- 投稿時間を"Posted XX minutes ago"のように表記-->
        Posted <%= time_ago_in_words(micropost.created_at) %> ago.
        <!-- ログインユーザーが投稿者と一致する場合 -->
        <% if current_user == micropost.user %>
            <!-- リンクにdeleteメソッドを指定してmicropostのURLにリクエスト -->
            <%= link_to "delete", micropost, method: :delete,
                                             data: { confirm: "You sure?" } %>
        <% end %>
    </span>
</li>

app/views/relationships/create.js.erb
<!-- createアクション後に実行されるJavaScriptファイルを作成-->
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

app/views/relationships/destroy.js.erb
<!-- destroyアクション後に実行されるJavaScriptファイルを作成-->
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");

app/views/shared/_error_messages.html.erb
<%# @userにエラーがある場合 %>
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            <!-- pluralize: 複数形に変換する。例）The form contains 3 errors. -->
            The form contains <%= pluralize(object.errors.count, "error") %>.
        </div>
        <ul>
            <%# エラーメッセージを全て表示 %>
            <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <!-- エラーがあれば表示-->
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
        <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    </div>
    <%= f.submit "Post", class:"btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<!-- ログインユーザーのgravatarへのリンクを縦横50pxで表示、current_userを渡す -->
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<!-- ユーザーの詳細画面へのリンク -->
<span><%= link_to "view my profile", current_user %></span>
<!-- 複数形に変換：ログインユーザーの投稿数を表示-->
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/home.html.erb
<% if logged_in? %>
    <div class="row">
        <aside class="col-md-4">
            <section class="user_info">
                <%= render 'shared/user_info' %>
            </section>
            <section class="micropost_form">
                <%= render 'shared/micropost_form' %>
            </section>
        </aside>
    </div>
<% else %>
    <div class="center jumbotron">
        <h1>Welcome to the Microposts</h1>
        
        <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    </div>
<% end %>

app/views/users/_follow.html.erb
<!-- remote: trueで、Ajax通信を可能にする -->
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
    <!-- フォローするユーザーのidを非表示で持つ -->
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<!-- 現在のユーザーが@userではない場合 -->
<% if current_user != @user %>
    <div id="follow_form">
    <!-- 現在のユーザーが@userをフォローしている場合 -->
    <% if current_user.following?(@user) %>
        <!-- アンフォローボタンを表示 -->
        <%= render 'unfollow' %>
    <% else %>
        <!-- フォローしていない場合は、フォローボタンを表示 -->
        <%= render 'follow' %>
    <% end %>
    </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
    <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>Setteings</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            
            <%= f.label :name %>
            <%= f.text_field :name %>
            
            <%= f.label :email %>
            <%= f.text_field :email %>
            
            <%= f.label :profile %>
            <%= f.text_area :profile %>
            
            <%= f.label :location %>
            <%= f.text_field :location %>
            
            <%= f.submit "Update my account", class: "btn btn-large btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/followers.html.erb
<h1>followers</h1>

<!-- followersが空でない場合 -->
<% if @follower_users.any? %>
<div class="row">
    <ol class="followers">
    <% @follower_users.each do |follower| %>
       <li class="folower">
            <div class="col-md-2 col-md-offset-2">
                <!-- Gravatarへのリンクを表示 -->
                <%= link_to gravatar_for(follower, size: 50), follower %>
            </div>
            <!-- ユーザーの詳細画面へのリンクを表示 -->
            <span class="user col-md-4">
                <%= link_to follower.name, follower %>
            </span>
        </li>
    <% end %>
    </ol>
<% end %>
</div>

app/views/users/followings.html.erb
<h1>followings</h1>

<!-- followingsが空でない場合 -->
<% if @following_users.any? %>
<div class="row">
    <ol class="followings">
    <% @following_users.each do |following| %>
       <li class="following">
            <div class="col-md-2 col-md-offset-2">
                <!-- Gravatarへのリンクを表示 -->
                <%= link_to gravatar_for(following, size: 50), following %>
            </div>
            <!-- ユーザーの詳細画面へのリンクを表示 -->
            <span class="user col-md-4">
                <%= link_to following.name, following %>
            </span>
        </li>
    <% end %>
    </ol>
<% end %>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%# フォームを生成 %>
        <%= form_for(@user) do |f| %>
            <%# 部分テンプレートerror_messagesを呼び出し、object (@user) を渡す %>
            <%= render 'shared/error_messages', object: f.object %>
            
            <%= f.label :name %>
            <%= f.text_field :name %>
            
            <%= f.label :email %>
            <%= f.text_field :email %>
            
            <%= f.label :password %>
            <%= f.password_field :password %>
            
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation %>
            
            <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <!-- Gravatarを表示 -->
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
        </section>
        <section class="col-md-4">
            <% if @following_users == nil %>
                <%= link_to("0 followings", followings_user_path) %>
            <% else %>
                <%= link_to("#{@following_users.count} followings", 
                           followings_user_path) %>
            <% end %>
        </section>
        <section class="col-md-4 col-md-offset-1">
            <% if @follower_users == nil %>
                <%= link_to("0 followers", followers_user_path) %>
            <% else %>
                <%= link_to("#{@follower_users.count} followers",
                            followers_user_path) %>
            <% end %>
        </section>
    </aside>
    <div class="col-md-8">
        <!-- ログインしている（かつ自分の詳細ページでない）場合は、フォロー/アンフォローボタンを表示 -->
        <%= render 'follow_form' if logged_in? %>
        <!-- ユーザーの投稿が空でない場合 -->
        <% if @user.microposts.any? %>
            <h3>Microposts (<%= @user.microposts.count %>)</h3>
            <ol class="microposts">
                <!-- micropostパーシャルに@micropostsを渡して表示 -->
                <%= render @microposts %>
            </ol>
        <% end %>
    </div>
</div>